[package]
name = "common"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "common"
path = "src/lib.rs"

[features]
default = []
user = [ "aya" ]

[dependencies]
aya = { version = "0.13.1", optional=true }
