name: build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  rust-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rust-src, clippy, rustfmt
        override: false

    - name: Install bpf-linker
      run: |
        cargo install bpf-linker

    # TODO: Once we migrate the controller from Go to Rust,
    # add the controller build step here.

    - name: Build all rust crates (dataplane, test server) 
      run: |
        make build

    - name: Check formatting
      run: |
        make check.format

    - name: Check clippy
      run: |
        make lint

    - name: Run Tests
      run: |
        make test

  docker-build-amd64:
    name: docker-build-amd64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dataplane:
              - 'dataplane/**'
            containerfile:
              - 'build/Containerfile.dataplane'
      - name: Setup QEMU
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--debug"
      - name: Build container image for amd64
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        uses: docker/build-push-action@v6
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64
          file: build/Containerfile.dataplane
          tags: kong/blixt-dataplane:pr-${{ github.event.pull_request.number }}-amd64-${{ github.sha }}

  docker-build-arm64:
    name: docker-build-arm64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dataplane:
              - 'dataplane/**'
            containerfile:
              - 'build/Containerfile.dataplane'
      - name: Setup QEMU
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--debug"
      - name: Build container image for arm64
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        uses: docker/build-push-action@v6
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/arm64
          file: build/Containerfile.dataplane
          tags: kong/blixt-dataplane:pr-${{ github.event.pull_request.number }}-arm64-${{ github.sha }}
